# version: "3"
# services:
#   cybergangs:
#     container_name: user-manual-destraislas
#     hostname: user-manual-destraislas
#     # image: cybergangs
#     build: ./
#     restart: always
#     ports:
#       - 3030:3030
#     #volumes:
#     #  - "./front:/usr/share/nginx/html"
#     # networks:
#     #   - proxy_red_principal
#     environment:
#       VIRTUAL_HOST: localhost:3030
#       VIRTUAL_PORT: 3030
#       LETSENCRYPT_HOST: localhost:3030
#       PUBLIC_URL: "http://localhost:3030"
# # networks:
# #   proxy_red_principal:
# #     external: true

version: '3'

services:
  docusaurus:
    image: node:1  # Puedes cambiar la versión de la imagen de Node según tus necesidades
    working_dir: /app
    ports:
      - "3000:3000"  # Ajusta el puerto según tus necesidades
    volumes:
      - ./docs:/app/docs  # Ajusta la ruta del volumen según la estructura de tu proyecto
    command: bash -c "cd /app/docs && npm install && npm start"